### ISSUE TITLE
Change slide effect to fade effect?

### ISSUE THREAD

**Issue by Vince-vegas** [glidejs/glide#484] opened 2020-04-26 21:03 UTC
Hi I'm trying to figured it out on how can i change the slide effect into Fade effect when i click buttons or autoplay it like SlickJs have

Can someone help me how can i change it to fade effect I'm using it on my Main Page

**Comment by markusguenther** [comment] 2020-05-12 14:31
I disabled the animationDuration and used CSS to do that on my own.
Feels bit hacky but it works.

**Comment by frankie-tech** [comment] 2020-10-14 13:26
Maybe this will help? https://github.com/glidejs/glide/issues/369#issuecomment-554668906 I've used it in the past, and its worked fine for me on v3

**Comment by jedrzejchalubek** [comment] 2021-11-22 23:22
Duplicate of https://github.com/glidejs/glide/issues/369

**Closed by jedrzejchalubek** 2021-11-22 23:22 UTC
